"""Changed first_name and last_name data typ

Revision ID: 0212713f74d3
Revises: 1820b4f1088a
Create Date: 2019-07-12 20:09:22.983523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0212713f74d3'
down_revision = '1820b4f1088a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_ibfk_1', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_ibfk_1', 'address', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
