"""New DB

Revision ID: 08faa14338cc
Revises: 
Create Date: 2019-06-29 14:05:38.412918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08faa14338cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ISBN', sa.String(length=13), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('publication_year', sa.String(length=4), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('ratings_count', sa.Integer(), nullable=False),
    sa.Column('rating_1', sa.Integer(), nullable=True),
    sa.Column('rating_2', sa.Integer(), nullable=True),
    sa.Column('rating_3', sa.Integer(), nullable=True),
    sa.Column('rating_4', sa.Integer(), nullable=True),
    sa.Column('rating_5', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ISBN'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=25), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('books')
    op.drop_table('author')
    # ### end Alembic commands ###
