"""empty message

Revision ID: 0afb6a31d421
Revises: 
Create Date: 2019-07-28 11:06:40.872969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0afb6a31d421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists1')
    op.drop_table('wishlists2')
    op.drop_table('wishlists3')
    op.add_column('wishlists', sa.Column('books', sa.String(length=13), nullable=True))
    op.drop_constraint('wishlists_ibfk_2', 'wishlists', type_='foreignkey')
    op.create_foreign_key(None, 'wishlists', 'books', ['books'], ['ISBN'])
    op.drop_column('wishlists', 'ISBN')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('ISBN', mysql.VARCHAR(length=13), nullable=False))
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.create_foreign_key('wishlists_ibfk_2', 'wishlists', 'books', ['ISBN'], ['ISBN'])
    op.drop_column('wishlists', 'books')
    op.create_table('wishlists3',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ISBN', mysql.VARCHAR(length=13), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], name='wishlists3_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists3_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wishlists2',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ISBN', mysql.VARCHAR(length=13), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], name='wishlists2_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists2_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wishlists1',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ISBN', mysql.VARCHAR(length=13), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], name='wishlists1_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists1_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
