"""first migration

Revision ID: 5338627d6d0d
Revises: 
Create Date: 2019-07-26 00:11:27.817394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5338627d6d0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('ISBN', sa.String(length=13), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('releaseDate', sa.Text(), nullable=True),
    sa.Column('soldUnits', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ISBN'),
    sa.UniqueConstraint('ISBN')
    )
    op.create_table('cart',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=13), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=13), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment__info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_number', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cardholder', sa.String(length=30), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('csv', sa.Integer(), nullable=False),
    sa.Column('ZIP', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_items',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=13), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('wishlists', sa.Column('books', sa.String(length=13), nullable=True))
    op.create_foreign_key(None, 'wishlists', 'books', ['books'], ['ISBN'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.drop_column('wishlists', 'books')
    op.drop_table('saved_items')
    op.drop_table('payment__info')
    op.drop_table('orders')
    op.drop_table('cart')
    op.drop_table('books')
    # ### end Alembic commands ###
