"""Importing to real books tableB

Revision ID: 83c075b07b58
Revises: 0a2e5e94e033
Create Date: 2019-06-29 15:27:19.933644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c075b07b58'
down_revision = '0a2e5e94e033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_temp',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('ISBN', sa.TEXT(), nullable=True),
    sa.Column('stock', sa.TEXT(), nullable=True),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('publication_year', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('language_code', sa.TEXT(), nullable=True),
    sa.Column('average_rating', sa.TEXT(), nullable=True),
    sa.Column('ratings_count', sa.TEXT(), nullable=True),
    sa.Column('rating_1', sa.TEXT(), nullable=True),
    sa.Column('rating_2', sa.TEXT(), nullable=True),
    sa.Column('rating_3', sa.TEXT(), nullable=True),
    sa.Column('rating_4', sa.TEXT(), nullable=True),
    sa.Column('rating_5', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
