"""empty message

Revision ID: b931de9d760f
Revises: 
Create Date: 2019-07-28 00:02:49.851919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b931de9d760f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment__info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_number', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cardholder', sa.String(length=30), nullable=False),
    sa.Column('expiration_date', sa.String(length=5), nullable=False),
    sa.Column('csv', sa.Integer(), nullable=False),
    sa.Column('ZIP', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment__info')
    # ### end Alembic commands ###
