"""updating db

Revision ID: f100976818ce
Revises: 
Create Date: 2019-07-25 22:20:39.605502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f100976818ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=13), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=13), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment__info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_number', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cardholder', sa.String(length=30), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('csv', sa.Integer(), nullable=False),
    sa.Column('ZIP', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_items',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=13), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['books.ISBN'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('books', sa.String(length=13), nullable=True),
    sa.ForeignKeyConstraint(['books'], ['books.ISBN'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blog_post', sa.Column('book_isbn', sa.String(length=140), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('books', sa.Column('releaseDate', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('soldUnits', sa.Integer(), nullable=True))
    op.drop_column('books', 'ratings_2')
    op.drop_column('books', 'ratings_4')
    op.drop_column('books', 'ratings_1')
    op.drop_column('books', 'ratings_5')
    op.drop_column('books', 'average_rating')
    op.drop_column('books', 'small_image_url')
    op.drop_column('books', 'publication_year')
    op.drop_column('books', 'ratings_3')
    op.drop_column('books', 'stock')
    op.drop_column('books', 'ratings_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ratings_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('ratings_3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publication_year', mysql.VARCHAR(length=4), nullable=True))
    op.add_column('books', sa.Column('small_image_url', mysql.TEXT(), nullable=False))
    op.add_column('books', sa.Column('average_rating', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('books', sa.Column('ratings_5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('ratings_1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('ratings_4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('ratings_2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('books', 'soldUnits')
    op.drop_column('books', 'releaseDate')
    op.drop_column('books', 'rating')
    op.drop_column('books', 'publisher')
    op.drop_column('blog_post', 'book_isbn')
    op.drop_table('wishlists')
    op.drop_table('saved_items')
    op.drop_table('payment__info')
    op.drop_table('orders')
    op.drop_table('cart')
    # ### end Alembic commands ###
