"""Added addresses

Revision ID: fa7f58215c49
Revises: 
Create Date: 2019-07-12 03:59:41.310939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa7f58215c49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('phone_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('addresses')
    op.drop_table('good_books')
    op.alter_column('books', 'author',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('books', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('books', 'genre',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('books', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('books', 'publication_year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('books', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint(None, 'books', ['ISBN'])
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('email_UNIQUE', table_name='users')
    op.drop_index('username_UNIQUE', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username_UNIQUE', 'users', ['username'], unique=True)
    op.create_index('email_UNIQUE', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('books', 'publication_year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('books', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               nullable=False)
    op.alter_column('books', 'genre',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('books', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('books', 'author',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_table('good_books',
    sa.Column('isbn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('authors', mysql.TEXT(), nullable=True),
    sa.Column('publication_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('original_title', mysql.TEXT(), nullable=True),
    sa.Column('language_code', mysql.TEXT(), nullable=True),
    sa.Column('average_rating', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('ratings_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ratings_1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ratings_2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ratings_3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ratings_4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ratings_5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_url', mysql.TEXT(), nullable=True),
    sa.Column('small_image_url', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('isbn'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('addresses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('address', mysql.TINYTEXT(), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('zip_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('address')
    # ### end Alembic commands ###
